### ISSUE TITLE
Logo for ByteConvert

### ISSUE THREAD

**Issue by familqasimov** [SloCompTech/ByteConvert_arduino#3]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want a change please specify. 

![byte converter](https://user-images.githubusercontent.com/36432269/39372660-0bc0b9d6-4a56-11e8-871b-e2dc8b920b9d.png)

**Comment by SloCompTech** [comment]
Hi,
awesome, design is really good. I really like color variations, which one would you recommend ?

**Comment by familqasimov** [comment]
If you ask me, blue looks nice :)

**Comment by SloCompTech** [comment]
Agree, will you create a pull request with new logo ? Create subdirectory `extras/graphics` and put logo in different formats there, Then link image at the top of readme with `<p align="center"><img src="extras/graphics/logo.png" alt="Byteconvert" height="200px"></p>`.

**Comment by familqasimov** [comment]
Ok. Sir, which sizes and file types will I add?

**Comment by SloCompTech** [comment]
PNG format will be ok, make two different size one a little biger than the other, about what size of logo I don't have a lot of experience with graphic design to tell so I leave that to you.

**Comment by familqasimov** [comment]
Sir, I sent you PR

**Comment by SloCompTech** [comment]
Thanks for your contribution, changes were merged.

**Comment by familqasimov** [comment]
Thanks for like and merged logo. Good luck

**Comment by SloCompTech** [comment]
Good look to you too.

**Comment by SloCompTech** [comment]
@familqasimov  Would you please make pull request for https://github.com/SloCompTech/ByteConvert_cpp too ?

**Comment by familqasimov** [comment]
Ok my friend :)
